version: '3.8'

services:
  backend:
    build:
      context: ./python-websocket-server
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./python-websocket-server/src:/app/src
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    image: nginx:alpine
    container_name: frontend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    expose:
      - "80"

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend